name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install the Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze --no-fatal-infos --fatal-warnings --no-pub

      - name: Verify formatting
        run: dart format --output=write .

      - name: Push changes
        run: |
          git config user.name "DartlyCorrectBot"
          git config user.email "yourdartcodeiswronglyformatted@juanarreglatucodigo.wtf"
          git add .
          git commit -m "Apply automatic formatting via GitHub Actions" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
